paths:
  adsorbate:      "../../structures/DIPAS.vasp"
  output_prefix:  "dipas_test"

engine:
  potential:
    backend: "mace"
    device:  "cpu"
    dtype:   "float32" # float32 is faster for testing
    model:   "small"   # small is faster
    d3:      false

  relaxation:
    fmax:      0.1
    steps:     50
    optimizer: "FIRE"

analysis:
  vibrational:
    displacement_ang: 0.01
    mode_refinement:
      enabled:            true
      max_iter:           2
      fmax:               0.1
      steps:              50
      freq_threshold_thz: -0.1
      perturbation_alpha: 0.1
